sudo: required
node_js:
  - "11.10.1"
services: 
  - docker
before_install: 
  - docker build -t alvinhui2018/docker-react -f Dockerfile.dev .
script:
  - docker run alvinhui2018/docker-react npm run test -- --coverage