sudo: required

services: 
  - docker

before_install: 
  - docker build -t alvinhui2018/docker-react -f Dockerfile.dev .

script:
  - docker run alvinhui2018/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "eb-docker-react"
  env: "EbDockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-123507475853"
  bucket_path: "eb-docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
